### ISSUE TITLE
  Android is sending NULL verbiage for group text.

### ISSUE THREAD

**Issue by choreilly123** [choreilly123/dot#4]

**Comment by shawnlauzon** [comment]
Can you provide more information on this? Perhaps a screen shot?

**Comment by shawnlauzon** [comment]
@choreilly123 bump ^

**Comment by shawnlauzon** [comment]
Ahh, now that I looked into this, it's exactly what you said: I was literally sending NULL (well actually `undefined`) to the SMS. Now that I fixed this, it should be sending the right info.

**Comment by choreilly123** [comment]
The group text works great with Android.  For iPhone, it is making the user hit send on each time.  I am using the "Famiy" menu option (first one under SME).  Feel free to use this same group for testing.  Photo attached.   There are 7 phone numbers.  It made me press the send (blue up arrow) seven times.  This was not the case on Android.

![img_3496](https://cloud.githubusercontent.com/assets/23065743/23735919/03243d86-0446-11e7-926b-8ffb8fd40c1b.PNG)

**Comment by shawnlauzon** [comment]
Ok, I'll take a look at it this weekend.
