### ISSUE TITLE
Wrong Password or ID - no notification

### ISSUE THREAD

**Issue by choreilly123** [choreilly123/dot#9]
Now when I enter an incorrect password or user ID, it no longer gives me the message.  It just goes to a white screen.

**Comment by choreilly123** [comment]
This should be the last thing, and I can roll out!  Please let me know when you have a new update.  Thanks!

**Comment by shawnlauzon** [comment]
Ok, yes this was a regression when I made another change a couple months ago. I'll fix it as 2.1.0.
